### ISSUE TITLE
change the size of chunk to 80 and asleep 3s to avoid flood

### ISSUE THREAD

**Issue by qiangweihewu** [RuslanUC/TelegramFTP#1]
Hi there!
Thanks for your project!

I met an error while tried to use it which said:

pyrogram.errors.exceptions.flood_420.FloodWait: Telegram says: [420 FLOOD_WAIT_X] - A wait of 20 seconds is required (caused by "messages.SendMedia")

So, I made some changes to the file pathio.py like 
line 87: 
async for data in stream.iter_by_block(1024*1024*80): 
line 94
await asleep(3)
line 112
for _o in range(o, o+80)
line 114
o += 80

then it works!

However, there is still a problem:
the FTP client wouldn't stop automatically after finishing upload; instead, it would restart the same upload(s) again, here are the logs:

Task exception was never retrieved
future: <Task finished name='Task-5205' coro=<MongoDBUserManager.notify_logout() done, defined at /www/bot/TelegramFTP/ftp/server.py:113> exception=ValueError('Too many releases')>
Traceback (most recent call last):
  File "/www/bot/TelegramFTP/ftp/server.py", line 114, in notify_logout
    self.available_connections[user].release()
  File "/www/bot/TelegramFTP/ftp/server.py", line 171, in release
    raise ValueError("Too many releases")
ValueError: Too many releases
Task exception was never retrieved
future: <Task finished name='Task-5208' coro=<MongoDBUserManager.notify_logout() done, defined at /www/bot/TelegramFTP/ftp/server.py:113> exception=ValueError('Too many releases')>
Traceback (most recent call last):
  File "/www/bot/TelegramFTP/ftp/server.py", line 114, in notify_logout
    self.available_connections[user].release()
  File "/www/bot/TelegramFTP/ftp/server.py", line 171, in release
    raise ValueError("Too many releases")
ValueError: Too many releases

Could you give suggestions on how to make it stop after finishing upload? Thanks!

**Comment by RuslanUC** [comment]
Try with latest commit.
